name: Cypress Tests

on: 
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress
        run: |
          npm ci

      - name: Cypress tests
        run: npm run test:chrome
        continue-on-error: false
        
        
